version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=fizzbuzz
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - fizzbuzz-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d postgres"]
      interval: 2s
      timeout: 2s
      retries: 20
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history
      - DB_SOURCE=postgresql://root:secret@postgres:5432/fizzbuzz?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fizzbuzz-network

volumes:
  data:
networks:
  fizzbuzz-network:
