// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"encoding/json"
	"time"
)

type FizzbuzzStatistic struct {
	Request   json.RawMessage `json:"request"`
	Count     int64           `json:"count"`
	UpdatedAt time.Time       `json:"updated_at"`
	CreatedAt time.Time       `json:"created_at"`
}
