// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ebaudet/go-fizz-buzz/db/sqlc (interfaces: Store)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	db "github.com/ebaudet/go-fizz-buzz/db/sqlc"
	gomock "github.com/golang/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// GetMostUsedRequest mocks base method.
func (m *MockStore) GetMostUsedRequest(arg0 context.Context) (db.FizzbuzzStatistic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMostUsedRequest", arg0)
	ret0, _ := ret[0].(db.FizzbuzzStatistic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMostUsedRequest indicates an expected call of GetMostUsedRequest.
func (mr *MockStoreMockRecorder) GetMostUsedRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMostUsedRequest", reflect.TypeOf((*MockStore)(nil).GetMostUsedRequest), arg0)
}

// IncrementRequest mocks base method.
func (m *MockStore) IncrementRequest(arg0 context.Context, arg1 json.RawMessage) (db.FizzbuzzStatistic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementRequest", arg0, arg1)
	ret0, _ := ret[0].(db.FizzbuzzStatistic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementRequest indicates an expected call of IncrementRequest.
func (mr *MockStoreMockRecorder) IncrementRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementRequest", reflect.TypeOf((*MockStore)(nil).IncrementRequest), arg0, arg1)
}
